apiVersion: v1
kind: ConfigMap
metadata:
  name: tpu-provisioner-manager
  namespace: tpu-provisioner-system
data:
  ENABLE_SLICE_CONTROLLER: "true"
  ENABLE_WEBHOOKS: "true"
  ENABLE_IMAGE_STREAMING: "false"