apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        volumeMounts:
        - name: certs
          readOnly: true
          mountPath: "/certs"
      volumes:
      - name: certs
        secret:
          secretName: webhook-server-tls
