apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: tpu-provisioner-system
  annotations:
    iam.gke.io/gcp-service-account: tpu-provisioner@{GCP_PROJECT_ID}.iam.gserviceaccount.com